service: views-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-1:797377682706:table/views"
package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: get_views
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: put_view
          method: put

resources: 
    Resources:
      viewsTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: views
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  
plugins:
- serverless-python-requirements
