service: post-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/*"
package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: posts/create
          method: post
  get:
    handler: handler.get
    events:
      - http:
          path: posts/get
          method: get
  all:
    handler: handler.all
    events:
      - http:
          path: posts/all
          method: get
  update:
    handler: handler.update
    events:
      - http:
          path: posts/update
          method: put
  delete:
    handler: handler.delete
    events:
      - http:
          path: posts/delete
          method: delete

resources: 
    Resources:
      postsTable: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: posts
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  
plugins:
- serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux